### ISSUE TITLE
Edit Landing page layout

### ISSUE THREAD

**Issue by pavergara5** [CS4-2016/tuklasbatangas#29]

**Comment by louiealmeda** [comment]
comment screenshot here

**Comment by jaeangelopb** [comment]
![screenshot_3](https://cloud.githubusercontent.com/assets/24486102/22933206/c8a668ba-f305-11e6-9d45-3396cafb7fd0.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/24486102/22933219/d06f6f56-f305-11e6-97f1-8f02055f5bfa.png)
Masyado pa pong mahaba ung short description namen kaya po na scroll pa po
